#!/usr/bin/env bash
# Generate the Xcode project. Run this after pulling, after changing
# project.yml, and after adding a file — the same moments `xcodegen generate`
# was run by hand.
#
# The one thing it does first: write the build number, as the number of
# commits behind HEAD. App Store Connect refuses an upload whose build number
# it has already seen, and the number had to be bumped by hand once per
# upload, which is a step that is only ever noticed by being forgotten — at
# the end of an archive, after the wait.
#
# Commit count is the right source: it cannot repeat, it goes up on its own,
# and it says something true about what is in the build. Archiving from a
# branch with fewer commits than the one already uploaded is the one case it
# gets wrong, and App Store Connect refuses that upload rather than taking it.
set -euo pipefail
cd "$(dirname "$0")/.."

build=$(git rev-list --count HEAD)
cat > Config/Build.xcconfig <<EOF
// Generated by scripts/generate.sh. Not in git — it is a fact about this
// checkout, not about the project.
CURRENT_PROJECT_VERSION = $build
EOF

echo "Build number $build"
xcodegen generate
